/**
 *   TokenKind is a simple enumeration of the different kinds of tokens
 *   
 */
package miniJava.SyntacticAnalyzer;

//public enum TokenKind {NUM, PLUS, TIMES, LPAREN, RPAREN, EOT, ERROR}

// new token kind
public enum TokenKind {NUM, LPAREN, RPAREN, EOT, ERROR,INTLITERAL,CHARLITERAL, ID,OPERATOR, ARRAY, BEGIN, CONST,DO,ELSE, END,FOR,FROM, FUNC,IF,INT,LET,OF, PROC, RECORD, 
	THEN,TO,TYPE,VAR,WHILE,CASE,DOT,COLON,SEMICOLON,COMMA, PERIOD,BECOMES, IS,LBRACKET, RBRACKET, LBRACE,RBRACE,LCURLY,RCURLY,FALSE,TRUE,NEW,CLASS,NULL,BOOLEAN
	,STRING,PRIVATE,PUBLIC,RETURN,STATIC,THIS,VOID,PACKAGE,SWITCH,THROW,THROWS,TRY,CATCH,ABSTRAT,CONTINUE,DEFAULT,BREAK,DOUBLE,IMPLEMENTS,PROTECTED,FLOAT,NATIVE,SUPER,SHORT				
	,EQUAL,PLUS,MINUS,TIMES,DIVIDE,REMAINDER,NOT,LESS,GREATER,LESSEQUAL,GREATEREQUAL,OR,AND,COMMENT,COMMENT2,NOTEQUAL,ASSIGN,GREATERTHAN,LESSTHAN}

